[main]
record = False

; CCTV RTSP URL or video file path
; vidInput = rtsp://admin:adybangun12@192.168.0.64:554
vidInput = video/salatiga/video.mp4
; vidInput = record/Kasus/original3.mp4
crop = True
direction = left   ; left / right 
encode = h265   ; h264 / h265 / mjpeg
drawRectangle = True
cropArea = [[145, 83], [741, 465]]
saveNoActivity = 10    ; in seconds
minHitTracker = 3  ; number of frames to confirm a track
maxAgeTracker = 15   ; number of frames to keep alive a track without associated detections3
thresholdTracker = 0.1   ; association threshold for the tracker


[model]
weights = weights/yolo11n-best.pt
confidence = 0.2    ; 0-1 scale


[ui]
viewScale = 1
windowName = CCTV YOLO Detection
windowCropName = CROPPED VIEW

fpsSet = 25   ; limit to maximum fps, 0 = unlimited
frameSkip = 1   ; skip frames, 0 = no skip
jumpSeconds = 20   ; jump seconds, 0 = no jump

fov = [[75, 8], [528, 338]]
boundLine = [200, 250]  ; y-axis position for counting line from fov